name: rede_social_pet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  brasil_fields: ^1.15.0
  email_validator: ^3.0.0
  flutter_carousel_widget: ^3.0.1
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/